SantiLl/easy_kitchen

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/models/user.rb, app/views/pages/home.html.erb, config/environments/development.rb, config/initializers/devise.rb, config/locales/devise.en.yml, config/routes.rb, db/migrate/20191028184923_devise_create_users.rb, db/schema.rb, test/models/user_test.rb
Installed devise gemfile
Created User devise model and router.
Added a form in application controller to let user put its name when registering.
User devise lets create users and login into them in the platform.
=> User devise added

app/controllers/kitchens_controller.rb, app/models/kitchen.rb, app/views/kitchens/create.html.erb, app/views/kitchens/index.html.erb, app/views/kitchens/new.html.erb, app/views/kitchens/show.html.erb, db/migrate/20191028181016_create_kitchens.rb, db/schema.rb, test/controllers/kitchens_controller_test.rb, test/models/kitchen_test.rb
cree el model y controller de kitchen. creo que esta terminado, revisalo y si te parece mandale pull!
=> Kitchen table

app/views/devise/confirmations/new.html.erb, app/views/devise/mailer/confirmation_instructions.html.erb, app/views/devise/mailer/email_changed.html.erb, app/views/devise/mailer/password_change.html.erb, app/views/devise/mailer/reset_password_instructions.html.erb, app/views/devise/mailer/unlock_instructions.html.erb, app/views/devise/passwords/edit.html.erb, app/views/devise/passwords/new.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/devise/shared/_error_messages.html.erb, app/views/devise/shared/_links.html.erb, app/views/devise/unlocks/new.html.erb
Todos los views de forms de sign in y sign up centrados
=> views de sign in y sign up centrados

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/kitchens_controller.rb, app/policies/application_policy.rb, app/policies/kitchen_policy.rb, test/policies/kitchen_policy_test.rb
Pundit implement only back end. we still have to implement pundit in front end in the views
=> implement back end pundit

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_kitchenbanner.scss, app/controllers/appointments_controller.rb, app/controllers/kitchens_controller.rb, app/javascript/packs/application.js, app/policies/appointment_policy.rb, app/views/appointments/new.html.erb, app/views/kitchens/show.html.erb, app/views/layouts/application.html.erb, db/migrate/20191029174607_change_date_type_in_appointments.rb, db/schema.rb, package.json, test/policies/appointment_policy_test.rb, yarn.lock
Desgined the kitchen show and implemented appointment booking. 
Added flatpickr js file so YARN INSTALL!
=> Appointment bookings

db/seeds.rb
=> seed corregida

app/assets/stylesheets/application.scss, app/views/components/_navbar.html.erb, app/views/kitchens/index.html.erb, app/views/pages/home.html.erb
=> Edit destroy

app/views/components/_card.html.erb, app/views/kitchens/show.html.erb
=> bugs corregidos

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_map.scss, app/views/kitchens/index.html.erb
=> kitchen index display done

app/views/kitchens/show.html.erb
Changed cloudinary image and setted as background image in banner
=> Kitchen show

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_kitchenbanner.scss, app/views/kitchens/show.html.erb
le agregue al show de kitchen la variante de que si es tuya la puedas editar o borrar y si no es tuya puedas hacer un appointment
=> edit and destroy action added to kitchen show

app/assets/stylesheets/components/_cardtrip.scss, app/assets/stylesheets/components/_index.scss, app/views/appointments/show.html.erb, app/views/components/_card-appointment.html.erb, db/seeds.rb
=> card appointment

app/controllers/reviews_controller.rb, app/policies/review_policy.rb, app/policies/user_policy.rb
Solved some vulnerabilities in all models edit/update/destroy
=> Pundit sercurity

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_text.scss, app/assets/stylesheets/config/_fonts.scss, app/controllers/kitchens_controller.rb, app/javascript/plugins/init_mapbox.js, app/models/review.rb, app/views/kitchens/_info_window.html.erb, app/views/kitchens/index.html.erb, app/views/kitchens/new.html.erb, app/views/kitchens/show.html.erb, app/views/layouts/application.html.erb
i have work in general style and also worked in the map and the markers
=> General style

app/assets/stylesheets/components/_cards.scss, app/views/kitchens/edit.html.erb, app/views/kitchens/new.html.erb
acoomode el espacio para escribir la description cuando editas o creas una kitchen y acomode los botons para editar y borrar en el kitchen show
=> Column kitchen

app/views/components/_appointment-card.html.erb, app/views/components/_dashboard-card.html.erb, app/views/components/_kitchen-appointments.html.erb, app/views/pages/dashboard.html.erb
Added features on dashboard index, solved some styles and bug fix
=> Dashboard kitchen appointments

app/views/components/_appointment-card.html.erb, app/views/components/_dashboard-card.html.erb, app/views/kitchens/show.html.erb
=> mensaje de conformacion de error listo

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_carousel.scss, app/views/components/_card.html.erb, app/views/kitchens/index.html.erb, app/views/shared/_carousel.html.erb, app/views/shared/_stars.html.erb
=> Home card index

app/controllers/kitchens_controller.rb, app/javascript/packs/application.js, app/views/kitchens/show.html.erb
Added json options which parse data form html form and disables it.
=> Added disabled dates in flatpicker when user appoints a kitchen

app/assets/stylesheets/components/_cards.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/pages/_index.scss, app/views/components/_card.html.erb, app/views/kitchens/_info_window.html.erb, app/views/kitchens/index.html.erb
cards on index responsive 
pop up on map corrected
=> maps and cards responsive
